name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile
        run: make

      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf

      # Deploy the PDF to GitHub Pages
      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Root directory of your repository
          destination_dir: '' # Leave empty to upload the file directly to the root of GitHub Pages
          keep_files: false # Overwrite existing content in the branch

